cla_bdx/urls.py
from django.urls import path, re_path
from .views import *

app_name = "cla_bdx"
urlpatterns = [
    path("bdx", CurrentCampaignView.as_view(), name="current"),  # Current campaigns
    re_path("election/(?P<type>[a-z_]+)", CampaignVoteView.as_view(), name="vote"),
    path("bdx/<int:campaign_pk>/box", CampaignVoteBoxView.as_view(), name="box"),
    path(
        "bdx/<int:campaign_pk>/calendar",
        CampaignCalendarView.as_view(),
        name="calendar",
    ),
    path("bdx/archives", LastCampaignView.as_view(), name="last"),  # All campaign list
]

cla_ca/urls.py
from django.urls import path, re_path
from .views import *

app_name = "cla_ca"
urlpatterns = [
    re_path("election/ca", ElectionVoteView.as_view(), name="vote"),
    path("ca/<int:election_pk>/box", ElectionVoteBoxView.as_view(), name="box")
]

cla_public/urls.py
from django.urls import path
from .views import *

app_name = "cla_public"
urlpatterns = [
    path("", IndexPublicView.as_view(), name="index")
]

cla_bdx/models.py
import os
import math
import uuid

from django.db import models
from django_resized import ResizedImageField
from django.contrib.auth.models import User
from django.utils.text import slugify
from django.utils import timezone

from cla_votes.const import CURSUS_CENTRALE, CURSUS_ITEEM, CURSUS_ENSCL


class FilePath:
    @classmethod
    def _path(cls, instance, pathlist, filename):
        ext = filename.split(".")[-1]
        filename = "%s-%s.%s" % (slugify(instance.name), uuid.uuid4(), ext)
        pathlist.append(filename)
        return os.path.join(*pathlist)

    @classmethod
    def program(cls, instance, filename):
        return cls._path(instance, ["cla_bdx", "program"], filename)

    @classmethod
    def logo(cls, instance, filename):
        return cls._path(instance, ["cla_bdx", "logo"], filename)

    @classmethod
    def regulation(cls, instance, filename):
        pathlist = ["cla_bdx", "regulation"]
        ext = filename.split(".")[-1]
        filename = "%s-%s.%s" % ("reglement", uuid.uuid4(), ext)
        pathlist.append(filename)
        return os.path.join(*pathlist)


class CampaignManager(models.Manager):
    def ongoing(self, type=None):
        if type is not None:
            return self.filter(
                type=type, starts_on__lt=timezone.now(), ends_on__gt=timezone.now()
            ).last()
        return self.filter(
            starts_on__lt=timezone.now(), ends_on__gt=timezone.now()
        ).last()

    def vote_ongoing(self, type=None):
        if type is not None:
            return self.filter(
                type=type,
                vote__starts_on__lt=timezone.now(),
                vote__ends_on__gt=timezone.now(),
            ).last()
        return self.filter(
            vote__starts_on__lt=timezone.now(), vote__ends_on__gt=timezone.now()
        ).last()


class Campaign(models.Model):
    objects = CampaignManager()

    class Meta:
        ordering = ("-starts_on",)
        verbose_name = "Campagne"

    class BDX(models.TextChoices):
        BDA = "bda", "BDA"
        BDE = "bde", "BDE"
        BDI = "bdi", "BDI"
        BDS = "bds", "BDS"
        BDA_ENSCL = "bda_enscl", "BDA ENSCL"
        BDE_ENSCL = "bde_enscl", "BDE ENSCL"

    starts_on = models.DateTimeField(verbose_name="Début")
    ends_on = models.DateTimeField(verbose_name="Fin")
    type = models.CharField(max_length=16, choices=BDX.choices, verbose_name="Campagne")

    @property
    def school_year(self):
        if 1 <= self.starts_on.month < 9:
            return self.starts_on.year - 1
        return self.starts_on.year

    def should_display_lists(self):
        return timezone.now() >= self.starts_on

    def should_display_vote(self):
        if not self.vote:
            return False
        return self.vote.starts_on <= timezone.now() < self.vote.ends_on

    def should_display_result(self):
        if not self.vote:
            return False
        return self.vote.display_result_on < timezone.now()

    def should_display_calendar(self):
        return self.ends_on > timezone.now()

    def can_user_vote(self, user: User):
        if self.type == Campaign.BDX.BDI:
            if user.infos.is_from_iteem():
                return True
        if self.type == Campaign.BDX.BDE:
            if user.infos.is_from_centrale():
                return True
        if self.type == Campaign.BDX.BDA:
            checks = [
                user.infos.is_from_centrale(),
                user.infos.is_from_iteem(),
                user.infos.is_from_enscl(),
            ]
            if any(checks):
                return True
        if self.type == Campaign.BDX.BDS:
            checks = [
                user.infos.is_from_centrale(),
                user.infos.is_from_iteem(),
                user.infos.is_from_enscl(),
            ]
            if any(checks):
                return True
        if self.type in {Campaign.BDX.BDA_ENSCL, Campaign.BDX.BDE_ENSCL}:
            if user.infos.is_from_enscl():
                return True

        return False

    def did_user_vote(self, user: User):
        return self.vote.votes.filter(user=user).count() > 0

    @property
    def calendar_starts_on(self):
        return self.starts_on

    @property
    def calendar_ends_on(self):
        return self.ends_on + timezone.timedelta(days=1)

    def __str__(self):
        return f"{self.type.upper()} {self.school_year}/{self.school_year+1}"


class List(models.Model):
    class Meta:
        verbose_name = "Liste"
        ordering = ("name",)

    campaign = models.ForeignKey(
        Campaign, related_name="lists", on_delete=models.CASCADE
    )
    name = models.CharField(max_length=100, verbose_name="Nom")
    logo = ResizedImageField(
        size=[500, 500],
        quality=90,
        upload_to=FilePath.logo,
        force_format="PNG",
        null=True,
        blank=True,
    )
    program = models.FileField(
        upload_to=FilePath.program, null=True, blank=True, verbose_name="Programme"
    )
    penality = models.FloatField(
        default=0, verbose_name="Pourcentage de voix de pénalité"
    )
    votes_binary = models.IntegerField(default=0)

    @property
    def votes_binary_final(self):
        return self.votes_binary - math.ceil(
            self.campaign.vote.total_votes * self.penality * 0.01
        )

    def vote_penality(self):
        return math.ceil(self.campaign.vote.total_votes * self.penality * 0.01)

    def __str__(self):
        return f"{self.name} - {self.campaign.type.upper()} {self.campaign.school_year}/{self.campaign.school_year+1}"


class Vote(models.Model):
    class Meta:
        verbose_name = "Vote"

    campaign = models.OneToOneField(
        Campaign, related_name="vote", on_delete=models.CASCADE
    )
    starts_on = models.DateTimeField(verbose_name="Début")
    ends_on = models.DateTimeField(verbose_name="Fin")
    display_result_on = models.DateTimeField(verbose_name="Publication des résultats")

    def register_user(self, user: User):
        VoteUser.objects.create(vote=self, user=user)

    @property
    def blank_votes(self):
        total = self.votes.count()
        for list in self.campaign.lists.all():
            total -= list.votes_binary
        return total

    @property
    def total_votes(self):
        return self.votes.count()

    @property
    def winner(self):
        if self.ends_on > timezone.now():
            return None

        score, winner = -1, None
        for list in self.campaign.lists.all():
            if list.votes_binary_final > score:
                score, winner = list.votes_binary_final, list
            elif list.votes_binary_final == score:
                winner = None
        return winner

    @property
    def participation_stats(self):
        participation_stats = {}

        if self.campaign.type == Campaign.BDX.BDI:
            participation_stats = {c: 0 for c in CURSUS_ITEEM}
        if self.campaign.type == Campaign.BDX.BDE:
            participation_stats = {c: 0 for c in CURSUS_CENTRALE}
        if self.campaign.type == Campaign.BDX.BDA:
            participation_stats = {
                c: 0 for c in CURSUS_CENTRALE + CURSUS_ITEEM + CURSUS_ENSCL
            }
        if self.campaign.type == Campaign.BDX.BDS:
            participation_stats = {
                c: 0 for c in CURSUS_CENTRALE + CURSUS_ITEEM + CURSUS_ENSCL
            }
        if self.campaign.type in {Campaign.BDX.BDA_ENSCL, Campaign.BDX.BDE_ENSCL}:
            participation_stats = {c: 0 for c in CURSUS_ENSCL}

        total = 0
        for c in participation_stats.keys():
            count = self.votes.filter(user__infos__cursus=c).count()
            participation_stats[c] = count
            total += count
        participation_stats["Autre"] = self.total_votes - total

        return participation_stats

    def __str__(self):
        return f"{self.campaign.type.upper()} {self.campaign.school_year}/{self.campaign.school_year+1}"


class VoteUser(models.Model):
    class Meta:
        verbose_name = "Vote Campagne BDX"

    vote = models.ForeignKey(Vote, related_name="votes", on_delete=models.CASCADE)
    user = models.ForeignKey(User, related_name="votes", on_delete=models.CASCADE)
    voted_on = models.DateTimeField(auto_now=True, null=True)


class CampaignRegulationManager(models.Manager):
    pass


class CampaignRegulation(models.Model):
    objects = CampaignRegulationManager()

    class Meta:
        verbose_name = "Règlement des campagnes"

    voted_on = models.DateField(verbose_name="Voté le")
    file = models.FileField(
        upload_to=FilePath.regulation, null=True, blank=True, verbose_name="Fichier PDF"
    )

    @property
    def school_year(self):
        if 1 <= self.voted_on.month < 9:
            return self.voted_on.year - 1
        return self.voted_on.year

    def __str__(self):
        return f"Réglement des campagnes {self.school_year}/{self.school_year+1}"

cla_public/views.py
from django.shortcuts import render
from django.views.generic import View

from cla_bdx.models import Campaign
from cla_ca.models import Election


class AbstractPublicView(View):

    def context(self, context=dict()):
        context["active_navigation"] = context.get("active_navigation", "accueil")
        return context


class IndexPublicView(AbstractPublicView):

    def get(self, req):
        on_going_campaign = Campaign.objects.ongoing()
        on_going_campaign_vote = Campaign.objects.vote_ongoing()
        on_going_election = Election.objects.ongoing()

        return render(
            req,
            "cla_public/index.html",
            self.context(
                {
                    "on_going_campaign": on_going_campaign,
                    "on_going_campaign_vote": on_going_campaign_vote,
                    "on_going_election": on_going_election,
                }
            ),
        )

cla_public/templates/cla_public/index.html
{% extends "layout/base.html" %}

{% block page_title %}CLA - Comité électoral{% endblock %}

{% block content %}
    {% if on_going_campaign_vote %}
        <div class="p-2 mt-2 container">
            <div class="card gradient-blue border-0">
                <div class="card-body">
                    <div class="row max-width-500 m-auto">
                        <div class="col-md-5 col-12">
                            <div class="inline-svg-container w-100 height-200 mb-2 mb-sm-0" data-src="{% url "cla_bdx:box" on_going_campaign_vote.pk %}"></div>
                        </div>
                        <div class="col-md-7 col-12 text-center">
                            <div class="d-flex h-100 align-items-center justify-content-center mt-2 mt-md-0">
                                <div>
                                    <h2 class="fs-30px">Vote en cours...</h2>
                                    <p>Le scrutin est ouvert jusqu'à {{ on_going_campaign_vote.vote.ends_on|date:"H" }}h</p>
                                    <a href="{% url "cla_bdx:vote" on_going_campaign_vote.type %}" class="btn btn-lg btn-outline-white">Voter !</a>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% elif on_going_election %}
        <div class="p-2 mt-2 container">
            <div class="card gradient-blue border-0">
                <div class="card-body">
                    <div class="row max-width-500 m-auto">
                        <div class="col-md-5 col-12">
                            <div class="inline-svg-container w-100 height-200 mb-2 mb-sm-0" data-src="{% url "cla_ca:box" on_going_election.pk %}"></div>
                        </div>
                        <div class="col-md-7 col-12 text-center">
                            <div class="d-flex h-100 align-items-center justify-content-center mt-2 mt-md-0">
                                <div>
                                    <h2 class="fs-30px">Vote en cours...</h2>
                                    <p>Le scrutin est ouvert jusqu'à {{ on_going_election.ends_on|date:"H" }}h</p>
                                    <a href="{% url "cla_ca:vote" %}" class="btn btn-lg btn-outline-white">Voter !</a>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% elif on_going_campaign %}
        <div class="p-2 mt-2 container">
            <div class="card border">
                <div class="card-body">
                    <div class="col-sm-6 col-12 text-sm-left text-center">
                        <h3>Campagnes {{ on_going_campaign.get_type_display }}</h3>
                        <p class="mb-0">{{ on_going_campaign.starts_on|date:"d/m/Y" }} - {{ on_going_campaign.ends_on|date:"d/m/Y" }}</p>
                    </div>
                    {% if on_going_campaign.should_display_lists %}
                        <div class="row mt-3">
                        {% for list in on_going_campaign.lists.all %}
                            {% if list_count == 1 %}
                                <div class="col-sm-12">
                            {% elif list_count == 2 %}
                                <div class="col-sm-6">
                            {% elif list_count == 3 %}
                                <div class="col-md-4">
                            {% else %}
                                <div class="col-sm-6">
                            {% endif %}
                        <div class="mt-3">
                            <div class="position-relative">
                                {% if list.logo %}
                                    <div style="max-width: 200px; margin: auto">
                                        <div class=""
                                             style="background: center / contain no-repeat url('{{ list.logo.url }}'); border-radius: 10px;/* width: calc(min(7vw, 7vh) * 300 / 100);*/ padding-bottom: calc(100% / 1); max-width: 100%;"></div>
                                    </div>
                                {% else %}
                                    <div class="position-relative m-auto bg-gradient-gray-400 d-flex align-items-center justify-content-center"
                                         style="border-radius: 10px; max-width: 200px; margin: auto; background-color: #f5f5f5;">
                                        <div class="top-0"
                                             style="/*width: calc(min(7vw, 7vh) * 300 / 100);*/ padding-bottom: calc(100% / 1); max-width: 100%;"></div>
                                        <div class="position-absolute text-white">
                                            <i class="fad fa-5x fa-shapes"></i>
                                        </div>
                                    </div>
                                {% endif %}
                            </div>
                        </div>
                        <div class="text-center mt-3">
                            <h4 class="mb-3">
                                {{ list.name }}
                            </h4>
                            {% if list.program %}
                                <a class="btn btn-outline-primary" href="{{ list.program.url }}" target="_blank">Programme électoral</a>
                            {% else %}
                                <a class="btn btn-outline-primary disabled">Programme non disponible</a>
                            {% endif %}
                        </div>
                        </div>
                        {% endfor %}
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
    {% endif %}

    <div class="p-2 mt-2 container">
        <div class="card">
            <div class="card-body">
                <p class="lead">
                    Bienvenue sur le site du comité électoral de Centrale Lille Associations.
                </p>
                <p>

                    Depuis l'onglet <i>Campagnes</i>, vous avez accès au <i>règlement des campagnes</i> en vigueur ainsi
                    qu'à la liste des campagnes de l'année scolaire en cours, dès leur officialisation.<br>
                    La page <i>Archives</i> regroupe les listes ayant participées aux campagnes BDX.<br>
                    Enfin, le moment venu, vous pourrez participer sur ce même site aux élections des futurs BDX et
                    membres du conseil d'administration de Centrale Lille Associations.
                </p>
                <h4 class="header-2">Le comité électoral</h4>
                <p>
                    Le comité électoral de Centrale Lille Associations, composé de 6 membres désignés par vote du CA élèves, joue différents rôles dans l'encadrement des campagnes
                    et l'organisation des élections :
                </p>
                <ul>
                    <li>
                        Suite à sa composition, il propose au vote du CA élèves <i>le règlement des campagnes</i> qui encadrera le déroulement de chaque campagne
                    </li>
                    <li>
                        Pendant toute la période précédant les campagnes, il accompagne toutes les listes en répondant à leurs questions et en les
                        guidant dans l'organisation de leur campagne
                    </li>
                    <li>
                        Il veille au respect du règlement par chaque liste, pendant toute la période des pré-campagnes où une stricte confidentialité doit
                        être respectée par les listes et pendant les campagnes elles mêmes
                    </li>
                    <li>
                        En cas de manquement au respect du règlement, il proposera au vote du CA élèves des sanctions appropriées
                    </li>
                    <li>
                        Il est chargé de l'organisation des votes, autant pour les campagnes BDX que pour l'élection du CA élèves, ainsi que du dévoilement du résultat des scrutins
                    </li>
                </ul>
            </div>
        </div>
    </div>

{% endblock %}