cla_ca/urls.py
from django.urls import path, re_path
from .views import *

app_name = "cla_ca"
urlpatterns = [
    re_path("election/ca", ElectionVoteView.as_view(), name="vote"),
    path("ca/<int:election_pk>/box", ElectionVoteBoxView.as_view(), name="box")
]

cla_customvotes/urls.py
from django.urls import path, re_path
from .views import *

app_name = "cla_customvotes"
urlpatterns = [
    path("votes/<str:vote_uuid>", ElectionVoteView.as_view(), name="vote"),
    path("votes/<str:vote_uuid>/procurations", ElectionVoteProxyView.as_view(), name="vote_proxy")
]

cla_public/urls.py
from django.urls import path
from .views import *

app_name = "cla_public"
urlpatterns = [
    path("", IndexPublicView.as_view(), name="index")
]

cla_customvotes/models.py
import os
import uuid

from django.db import models
from django_resized import ResizedImageField
from django.contrib.auth.models import User
from django.utils.text import slugify
from django.utils import timezone

from cla_votes.const import CURSUS_CENTRALE, CURSUS_ITEEM, CURSUS_ENSCL
from cla_auth.models import UserInfos


class FilePath:
    @classmethod
    def _path(cls, instance, pathlist, filename):
        ext = filename.split(".")[-1]
        filename = "%s-%s.%s" % (
            slugify(f"{instance.first_name} {instance.last_name}"),
            uuid.uuid4(),
            ext,
        )
        pathlist.append(filename)
        return os.path.join(*pathlist)

    @classmethod
    def photo(cls, instance, filename):
        return cls._path(instance, ["cla_customvotes", "photo"], filename)


class Election(models.Model):
    class Meta:
        ordering = ("-starts_on",)
        verbose_name = "Election"

    name = models.CharField(verbose_name="Nom du vote", max_length=150)
    starts_on = models.DateTimeField(verbose_name="Début de l'élection")
    ends_on = models.DateTimeField(verbose_name="Fin de l'élection")
    uuid = models.UUIDField(unique=True, default=uuid.uuid4, editable=False)
    is_active = models.BooleanField(
        default=False,
        verbose_name="Le vote est actif et accessible (dans le respect des dates d'ouverture)",
    )

    @property
    def school_year(self):
        if 1 <= self.starts_on.month < 9:
            return self.starts_on.year - 1
        return self.starts_on.year

    def should_access_vote(self):
        return self.starts_on <= timezone.now() < self.ends_on and self.is_active

    def has_user_proxy(self, user: User):
        return self.proxies.filter(user=user).count() > 0

    def get_user_proxy(self, user: User):
        return self.proxies.filter(user=user).first()

    def did_user_vote(self, user: User):
        return self.votes.filter(user=user).count() > 0

    def did_user_proxy_vote(self, user: User):
        return self.proxies.filter(user=user, voted_on__isnull=False).count() > 0

    def register_user(self, user: User):
        VoteUser.objects.create(vote=self, college=user.infos.college, user=user)

    @property
    def candidates_results(self):
        return self.candidates.order_by("-votes")

    @property
    def winner(self):
        best_candidate = None
        for candidate in self.candidates_results:
            if best_candidate is None:
                best_candidate = candidate
            else:
                if candidate.votes >= best_candidate.votes:
                    return None
        return best_candidate

    def blank_votes(self):
        total = self.total_votes()
        for candidate in self.candidates_results:
            total -= candidate.votes
        return total

    def total_votes(self):
        return self.votes.count() + self.total_proxies_votes()

    def total_proxies_votes(self):
        total = 0
        for proxy in self.proxies.filter(voted_on__isnull=False):
            total += proxy.total
        return total

    @property
    def participation_stats(self):
        participation_stats = {
            c: 0 for c in CURSUS_ITEEM + CURSUS_CENTRALE + CURSUS_ENSCL
        }

        total = 0
        for c in participation_stats.keys():
            count = self.votes.filter(user__infos__cursus=c).count()
            participation_stats[c] = count
            total += count
        participation_stats["Autre"] = self.total_votes() // 2 - total

        return participation_stats

    def __str__(self):
        return self.name


class Candidate(models.Model):
    class Meta:
        verbose_name = "Candidat"
        # ordering = "college", "last_name"

    election = models.ForeignKey(
        Election, related_name="candidates", on_delete=models.CASCADE
    )
    first_name = models.CharField(max_length=100, verbose_name="Prénom")
    last_name = models.CharField(max_length=100, verbose_name="Nom")
    photo = ResizedImageField(
        size=[300, 300],
        quality=80,
        upload_to=FilePath.photo,
        force_format="JPEG",
        null=True,
        blank=True,
    )
    votes = models.IntegerField(default=0)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"


class VoteUser(models.Model):
    class Meta:
        verbose_name = "Vote"
        ordering = ("user__last_name",)

    vote = models.ForeignKey(Election, related_name="votes", on_delete=models.CASCADE)
    college = models.CharField(max_length=16, choices=UserInfos.Colleges.choices)
    user = models.ForeignKey(
        User, related_name="votes_custom", on_delete=models.CASCADE
    )
    voted_on = models.DateTimeField(auto_now=True, null=True)


class VoteProxy(models.Model):
    class Meta:
        unique_together = (
            "vote",
            "user",
        )
        verbose_name = "Procuration"

    vote = models.ForeignKey(Election, related_name="proxies", on_delete=models.CASCADE)
    user = models.ForeignKey(
        User, related_name="votes_custom_proxies", on_delete=models.CASCADE
    )
    names = models.TextField(
        max_length=1000,
        verbose_name="Identités des procurants",
        help_text="Indiqué une personne par ligne",
    )
    voted_on = models.DateTimeField(default=None, null=True, editable=False)

    @property
    def total(self):
        return len(["" for name in self.names.split("\n") if len(name.strip()) > 0])

cla_customvotes/forms.py
from django import forms
from django.core.exceptions import ValidationError
from .models import Candidate


class CustomVoteForm(forms.Form):

    vote1 = forms.ChoiceField(
        label="Je vote pour",
        required=True,
        widget=forms.Select(attrs={'class': 'form-control'})
    )

    def __init__(self, *args, **kwargs):
        candidates = kwargs.pop('candidates')
        super().__init__(*args, **kwargs)
        choices = [(0, 'Aucun candidat (vote blanc)')]
        for candidate in candidates:
            choices.append((candidate.pk, f"{candidate.first_name} {candidate.last_name}"))
        self.fields['vote1'].choices = choices


class CustomVoteProxyForm(forms.Form):

    def __init__(self, *args, **kwargs):
        self.candidates = kwargs.pop('candidates')
        self.proxy = kwargs.pop('proxy')
        super().__init__(*args, **kwargs)

        self.mapping = {}
        for candidate in self.candidates:
            self.mapping[candidate.pk] = f"vote_{candidate.pk}"
            self.fields[f"vote_{candidate.pk}"] = forms.IntegerField(label=str(candidate), min_value=0)

        self.mapping[-1] = 'vote_blank'
        self.fields['vote_blank'] = forms.IntegerField(label="Votes blancs", min_value=0)

        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = "form-control"

    def clean_vote_blank(self):
        total = 0
        for name, value in self.cleaned_data.items():
            print(name, value)
            total += value
        print(total)
        if total != self.proxy.total:
            raise ValidationError(f"Vous devez répartir correctement vos {self.proxy.total} votes.")
        return self.cleaned_data['vote_blank']

    def get_vote_for(self, candidate: Candidate):
        return self.cleaned_data[self.mapping[candidate.pk]]

cla_customvotes/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import View
from django.http.response import Http404
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib import messages
from django.utils import timezone

from .models import *
from .forms import *


class AbstractCaView(View):

    def context(self, context=dict()):
        context['active_navigation'] = context.get('active_navigation', "ca")
        return context


@method_decorator(login_required, 'dispatch')
class ElectionVoteView(AbstractCaView):

    def get(self, req, vote_uuid):
        election = get_object_or_404(Election, uuid=vote_uuid)

        if not election.should_access_vote():
            return render(
                req,
                "cla_customvotes/member/vote_closed.html",
                self.context({
                    'election': election
                })
            )

        if election.did_user_vote(req.user):
            return self.render_already_vote(election)

        form = CustomVoteForm(candidates=election.candidates.all())

        return render(
            req,
            "cla_customvotes/member/vote.html",
            self.context({
                'election': election,
                'form': form
            })
        )

    def post(self, req, vote_uuid):
        election = get_object_or_404(Election, uuid=vote_uuid)

        if not election.should_access_vote():
            return render(
                req,
                "cla_customvotes/member/vote_closed.html",
                self.context({
                    'election': election
                })
            )

        if election.did_user_vote(req.user):
            return self.render_already_vote(election)

        form = CustomVoteForm(req.POST, candidates=election.candidates.all())

        if form.is_valid():

            candidate1_index = int(form.cleaned_data['vote1'])

            # Register user vote
            election.register_user(req.user)

            if candidate1_index > 0:
                try:
                    candidate1 = election.candidates.get(pk=candidate1_index)
                except Candidate.DoesNotExist:
                    messages.error(req, "Votre vote n'a été validé, veuillez réessayer.")
                    return redirect("cla_ca:vote")

                candidate1.votes = candidate1.votes + 1
                candidate1.save()

            return render(
                req,
                "cla_customvotes/member/did_vote.html",
                self.context({
                    'election': election,
                    'proxy': election.proxies.filter(user=req.user, voted_on__isnull=True).first()
                })
            )

        return render(
            req,
            "cla_customvotes/member/vote.html",
            self.context({
                'election': election,
                'form': form,
                'scroll': True
            })
        )

    def render_already_vote(self, election):
        return render(
            self.request,
            "cla_customvotes/member/already_vote.html",
            self.context({
                'election': election,
                'proxy': election.proxies.filter(user=self.request.user, voted_on__isnull=True).first()
            })
        )


@method_decorator(login_required, 'dispatch')
class ElectionVoteProxyView(AbstractCaView):

    def get(self, req, vote_uuid):
        election = get_object_or_404(Election, uuid=vote_uuid)

        if not election.should_access_vote():
            return render(
                req,
                "cla_customvotes/member/vote_closed.html",
                self.context({
                    'election': election
                })
            )

        if not election.has_user_proxy(req.user):
            return render(
                req,
                "cla_customvotes/member/vote_noproxy.html",
                self.context({
                    'election': election
                })
            )

        if election.did_user_proxy_vote(req.user):
            return self.render_already_vote(election)

        form = CustomVoteProxyForm(proxy=election.get_user_proxy(req.user), candidates=election.candidates.all())

        print(election.get_user_proxy(req.user))

        return render(
            req,
            "cla_customvotes/member/vote_proxy.html",
            self.context({
                'election': election,
                'form': form,
                'proxy': election.get_user_proxy(req.user)
            })
        )

    def post(self, req, vote_uuid):
        election = get_object_or_404(Election, uuid=vote_uuid)

        if not election.should_access_vote():
            return render(
                req,
                "cla_customvotes/member/vote_closed.html",
                self.context({
                    'election': election
                })
            )

        if not election.has_user_proxy(req.user):
            return render(
                req,
                "cla_customvotes/member/vote_noproxy.html",
                self.context({
                    'election': election
                })
            )

        if election.did_user_proxy_vote(req.user):
            return self.render_already_vote(election)

        form = CustomVoteProxyForm(req.POST, proxy=election.get_user_proxy(req.user), candidates=election.candidates.all())

        if form.is_valid():
            # First save the vote
            proxy: VoteProxy = form.proxy
            proxy.voted_on = timezone.now()
            proxy.save()

            # Then update candidates urns
            for candidate in election.candidates.all():
                candidate.votes += form.get_vote_for(candidate)
                candidate.save()

            return render(
                req,
                "cla_customvotes/member/did_vote.html",
                self.context({
                    'election': election
                })
            )

        return render(
            req,
            "cla_customvotes/member/vote_proxy.html",
            self.context({
                'election': election,
                'form': form,
                'scroll': True,
                'proxy': election.get_user_proxy(req.user)
            })
        )

    def render_already_vote(self, election):
        return render(
            self.request,
            "cla_customvotes/member/already_vote.html",
            self.context({
                'election': election,
                'proxy': election.proxies.filter(user=self.request.user, voted_on__isnull=True).first()
            })
        )

cla_customvotes/templates/cla_customvotes/member/access_refused.html
{% extends "layout/base.html" %}

{% block page_title %}
    Accès refusé
{% endblock %}

{% block content %}

    <div style="height: calc(75vh)" class="d-flex align-items-center justify-content-center">
        <div class="card">
            <div class="card-body">
                <div class="max-width-500 m-auto text-center p-3">
                    <p class="lead">
                        Vous n'avez pas de droit de vote pour cette élection.
                    </p>
                    <p class="mb-0">
                        <a href="{% url 'cla_public:index' %}">Retour</a>
                    </p>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

cla_customvotes/templates/cla_customvotes/member/already_vote.html
{% extends "layout/base.html" %}

{% block page_title %}
    A voté
{% endblock %}

{% block content %}

     <div style="height: calc(75vh)" class="d-flex align-items-center justify-content-center">
        <div class="card">
            <div class="card-body">
                <div class="max-width-500 m-auto text-center p-3">
                    <div class="alert alert-info mb-0">
                        <div class="d-flex align-items-center justify-content-center">
                            <div>
                                <h4 class="mb-0">Votre participation à cette élection a déjà été enregistrée.</h4>
                                {% if proxy %}
                                    <div class="text-center">
                                        <p class="mt-3">
                                            Vous pouvez maintenant procéder aux votes de vos procurations
                                        </p>
                                        <p>
                                            <a class="btn btn-primary" href="{% url "cla_customvotes:vote_proxy" election.uuid %}">Accéder</a>
                                        </p>
                                    </div>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

cla_customvotes/templates/cla_customvotes/member/did_vote.html
{% extends "layout/base.html" %}

{% block page_title %}
    {{ election }} : A voté
{% endblock %}

{% block content %}

    <div style="height: calc(75vh)" class="d-flex align-items-center justify-content-center">
        <div class="card">
            <div class="card-body">
                <div class="max-width-500 m-auto text-center p-3">
                    <div class="alert alert-success mb-0">
                        <div class="d-flex align-items-center justify-content-center">
                            <div class="mr-2">
                                <div>
                                    <i class="far fa-check-circle fa-2x"></i>
                                </div>
                            </div>
                            <div>
                                <h4 class="mb-0">Votre vote a bien été enregistré !</h4>
                            </div>
                        </div>
                        {% if proxy %}
                            <div class="text-center mt-4">
                                <p class="mb-1">
                                    Vous pouvez maintenant procéder aux votes de vos procurations
                                </p>
                                <p>
                                    <a class="btn btn-primary" href="{% url "cla_customvotes:vote_proxy" election.uuid %}">Accéder</a>
                                </p>
                            </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

cla_customvotes/templates/cla_customvotes/member/vote.html
{% extends "layout/base.html" %}

{% block page_title %}
    {{ election }} : Voter
{% endblock %}

{% block content %}
    <div class="p-2 mt-2 container">
        <div class="card">
            <div class="card-body">
                <form method="post" style="max-width: 1000px" class="m-auto">
                    {% csrf_token %}

                    <h3 class="text-center header-2 mb-4">{{ election }}</h3>

                    <p class="text-center mb-4">
                        Découvrez ci dessous tous les candidats à cette élection.
                    </p>

                    <div class="row justify-content-md-center">
                        {% for candidate in election.candidates.all %}
                            <div class="col-sm-12 col-md-5 col-lg-4">
                                {% if candidate.photo %}
                                    <div style="max-width: 200px; margin: 2rem auto 0">
                                        <div class=""
                                             style="background: center / contain no-repeat url('{{ candidate.photo.url }}'); border-radius: 20px;/* width: calc(min(7vw, 7vh) * 300 / 100);*/ padding-bottom: calc(100% / 1); max-width: 100%;"></div>
                                    </div>
                                {% else %}
                                    <div class="position-relative m-auto bg-gradient-gray-400 d-flex align-items-center justify-content-center" style="border-radius: 10px; max-width: 200px; margin: auto; background-color: #f5f5f5;">
                                        <div class="top-0" style="/*width: calc(min(7vw, 7vh) * 300 / 100);*/ padding-bottom: calc(100% / 1); max-width: 100%;"></div>
                                        <div class="position-absolute text-white">
                                            <i class="fad fa-5x fa-user"></i>
                                        </div>
                                    </div>
                                {% endif %}
                                <div class="text-center mt-3">
                                    <h4 class="mb-3">{{ candidate }}</h4>
                                </div>
                            </div>
                        {% empty %}
                            <p class="text-center" style="color: #707070">
                                Aucun candidat ne s'est présenté à cette élection
                            </p>
                        {% endfor %}
                    </div>

                    <hr>

                    <div class="max-width-500" style="margin: 2rem auto 0">

                        {% if messages %}
                            <div class="messages mt-4 mb-4">
                                {% for msg in messages %}
                                    <div class="alert alert-{{ msg.level_tag }} mb-2">
                                        {{ msg.message }}
                                    </div>
                                {% endfor %}
                            </div>
                        {% endif %}

                        {% if form.has_errors %}
                            <div class="messages mt-4 mb-4">
                                {% for error in form.errors %}
                                    <div class="alert alert-danger mb-2">
                                        {{ error }}
                                    </div>
                                {% endfor %}
                            </div>
                        {% endif %}

                        {% for field in form %}
                            <div class="form-group{% if field.errors %} is-invalid{% endif %}">

                                <label for="{{ field.id_for_label }}" style="font-weight: 600">{{ field.label }}</label>

                                {% if field.errors %}
                                    <div class="invalid-feedback">
                                        {% if field.errors|length > 1 %}
                                            <ul>
                                                {% for error in field.errors %}
                                                    <li>{{ error|escape }}</li>
                                                {% endfor %}
                                            </ul>
                                        {% else %}
                                            {{ field.errors.0|escape }}
                                        {% endif %}
                                    </div>
                                {% endif %}

                                {{ field }}

                                {% if field.help_text %}
                                    <p class="help">{{ field.help_text|safe }}</p>
                                {% endif %}
                            </div>
                        {% endfor %}

                        <p>
                            En cliquant sur "Voter", vous confirmez votre vote, sur lequel vous n'aurez plus aucun droit de modification.
                        </p>

                        <div class="text-right">
                            <button type="submit" class="btn btn-outline-primary">Voter</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

    {% if scroll %}
        <script>
            window.scrollTo(0, document.body.scrollHeight);
        </script>
    {% endif %}

{% endblock %}

cla_customvotes/templates/cla_customvotes/member/vote_closed.html
{% extends "layout/base.html" %}

{% block page_title %}
    Vote fermé
{% endblock %}

{% block content %}

    <div style="height: calc(75vh)" class="d-flex align-items-center justify-content-center">
        <div class="card">
            <div class="card-body">
                <div class="max-width-500 m-auto text-center p-3">
                    <p class="lead">
                        Ce vote est actuellement fermé
                    </p>
                    <p class="mb-0">
                        <a href="{% url 'cla_public:index' %}">Retour</a>
                    </p>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

cla_customvotes/templates/cla_customvotes/member/vote_noproxy.html
{% extends "layout/base.html" %}

{% block page_title %}
    Accès refusé
{% endblock %}

{% block content %}

    <div style="height: calc(75vh)" class="d-flex align-items-center justify-content-center">
        <div class="card">
            <div class="card-body">
                <div class="max-width-500 m-auto text-center p-3">
                    <p class="lead">
                        Vous n'avez aucun procuration pour cette élection
                    </p>
                    <p class="mb-0">
                        <a href="{% url 'cla_public:index' %}">Retour</a>
                    </p>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

cla_customvotes/templates/cla_customvotes/member/vote_proxy.html
{% extends "layout/base.html" %}

{% block page_title %}
    {{ election }} : Voter
{% endblock %}

{% block content %}
    <div class="p-2 mt-2 container">
        <div class="card">
            <div class="card-body">
                <form method="post" style="max-width: 1000px" class="m-auto">
                    {% csrf_token %}

                    <h3 class="text-center header-2 mb-4">{{ election }}</h3>

                    <p class="text-center mb-4">
                        Vous êtes responsables de {{ proxy.total }} vote{{ proxy.total|pluralize }} par procuration.<br>
                        Répartissez ces votes ci-dessous :
                    </p>

                    <div class="max-width-500" style="margin: 2rem auto 0">

                        {% if messages %}
                            <div class="messages mt-4 mb-4">
                                {% for msg in messages %}
                                    <div class="alert alert-{{ msg.level_tag }} mb-2">
                                        {{ msg.message }}
                                    </div>
                                {% endfor %}
                            </div>
                        {% endif %}

                        {% for field in form %}
                            <div class="form-group{% if field.errors %} is-invalid{% endif %}">

                                <label for="{{ field.id_for_label }}" style="font-weight: 600">{{ field.label }}</label>

                                {% if field.errors %}
                                    <div class="invalid-feedback">
                                        {% if field.errors|length > 1 %}
                                            <ul>
                                                {% for error in field.errors %}
                                                    <li>{{ error|escape }}</li>
                                                {% endfor %}
                                            </ul>
                                        {% else %}
                                            {{ field.errors.0|escape }}
                                        {% endif %}
                                    </div>
                                {% endif %}

                                {{ field }}

                                {% if field.help_text %}
                                    <p class="help">{{ field.help_text|safe }}</p>
                                {% endif %}
                            </div>
                        {% endfor %}

                        <p>
                            En cliquant sur "Voter", vous confirmez votre vote, sur lequel vous n'aurez plus aucun droit de modification.
                        </p>

                        <div class="text-right">
                            <button type="submit" class="btn btn-outline-primary">Voter</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

    {% if scroll %}
        <script>
            window.scrollTo(0, document.body.scrollHeight);
        </script>
    {% endif %}

{% endblock %}